### ISSUE TITLE
non-cuda bug

### ISSUE THREAD

**Issue by matthiasreisser** [toologicbv/meta_learner#1]
Fix Line 112 in rnn_optimizer.py from self.cuda to self.use_cuda

**Comment by toologicbv** [comment]
Thanks Matthias. Confusing, but it does not matter whether I change this. self.cuda == self.use_cuda. I could get rid of self.use_cuda though to get rid of this confusion.

**Comment by matthiasreisser** [comment]
self.cuda seems to be the method that transfers the variable to cuda. Therefore 
self.cuda always evaluates to "True".

**Comment by toologicbv** [comment]
because MetaLearner extends nn.Module it inherits the cuda() method that indeed transfers the "Module" parameters to cuda. But I used self.use_cuda indeed to have an indication whether the model uses cuda (to transfer other variables to cuda as well). But I think in the case you pointed out, I did a "bad copy" of the original version.
